server:
  port: 8080

#eureka:
#  instance:
#    hostname: configserver
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://discovery:8761/eureka/
spring:
  cloud:
    config:
      uri:
         http://myconfigserver.com